version: "3.4"
services:
  backend:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
      cache_from:
        - ubuntu:16.04
        - golang:1.12
    depends_on:
      - mysql
    image: qc-monitor:v1.0.0
    volumes:
      - ./storage:/app/storage
    ports:
      - "9090:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - Port: 9090
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: mysql-qc-monitor
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bW90aGVyIGZ1Y2tlciBub29i
      MYSQL_DATABASE: qc_monitor
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1
volumes:
  db_data:
    name: monitor_db_data
    external: true
